# Generated by Django 3.1 on 2020-09-02 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='viewcount',
            new_name='view_count',
        ),
    ]
